<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>


# Laboratorio de NumPy

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [1]:
import numpy as np

array_1d = np.arange(10)
print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [2]:
array_2d = np.reshape(array_1d,(2,5))
print(array_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [3]:
list=[0,2,0,3,0,4,0]
arraylist=np.array(list)
print(arraylist[arraylist > 0])

[2 3 4]


#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [4]:
array_3x3 = np.random.rand(3, 3)

print(array_3x3)

array_3x3x = np.random.randint(0,1,(3,3)) #random.randit(valor inicial,valor final mas 1 (filas,columnas))

print(array_3x3x)

[[0.32196889 0.08086742 0.15374365]
 [0.38040309 0.16375116 0.99714734]
 [0.5487535  0.64112693 0.39648978]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [5]:
array_ran10 = np.random.rand(1, 10)
print(array_ran10)
array_ran10x = np.random.randint(0,100,(1,10)) #random.randit(valor inicial,valor final mas 1 (filas,columnas))//si solo quieres una linea pones el numero de valores

print(array_ran10x)

print(np.max(array_ran10x),np.min(array_ran10x))


[[0.45860382 0.13891869 0.51624591 0.99501658 0.93215119 0.76483532
  0.97903291 0.74065208 0.68444572 0.01023894]]
[[57 68 58  4 25 25 54 95 29  2]]
95 2


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [6]:
array_ran = np.random.randint(0,100,10)

array_raninv = array_ran[::-1]
print(array_ran)
print(array_raninv)

[90 41  9 11 36 12 16  4 38 92]
[92 38  4 16 12 36 11  9 41 90]



#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [7]:
arraytridi=np.arange(1,25).reshape(2,3,4)
print(arraytridi)
print("-----------------")
num15=arraytridi[arraytridi==15]
print(num15)
print("-----------------")
primerarray=arraytridi[0]
print(primerarray)
print("-----------------")
ultimafila=arraytridi[1][2]
print(ultimafila)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
-----------------
[15]
-----------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
-----------------
[21 22 23 24]



#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [8]:
arraytridi2=np.arange(1,31).reshape(3,2,5)
print(arraytridi2)
print("-----------------")

subarray1=arraytridi2[0,:2,:2]
print(subarray1)
print("-----------------")

subarray2=arraytridi2[2,:2]
print(subarray2)
print("-----------------")

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]]
-----------------
[[1 2]
 [6 7]]
-----------------
[[21 22 23 24 25]
 [26 27 28 29 30]]
-----------------


#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [9]:
arraytridi3=np.arange(1,25).reshape(4,3,2)
print(arraytridi3)
print("-----------------")
arraytridi3[1,1,:]=0
print(arraytridi3)
print("-----------------")
arraytridi3[3,:,:]=-1
print(arraytridi3)
print("-----------------")

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]
-----------------
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 0  0]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]
-----------------
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 0  0]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[-1 -1]
  [-1 -1]
  [-1 -1]]]
-----------------



#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [10]:
arraytridi4=np.arange(-10,14).reshape(2,4,3)
print(arraytridi4)
print("-----------------")
mayor5=arraytridi4[arraytridi4>=5]
print(mayor5)
print("-----------------")
arraytridi4[arraytridi4 <= 0] = 0
print(arraytridi4)


[[[-10  -9  -8]
  [ -7  -6  -5]
  [ -4  -3  -2]
  [ -1   0   1]]

 [[  2   3   4]
  [  5   6   7]
  [  8   9  10]
  [ 11  12  13]]]
-----------------
[ 5  6  7  8  9 10 11 12 13]
-----------------
[[[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  1]]

 [[ 2  3  4]
  [ 5  6  7]
  [ 8  9 10]
  [11 12 13]]]


#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [11]:
arraytridi5=np.arange(1,28).reshape(3,3,3)
print(arraytridi5)
print("-----------------")
arayyy=arraytridi5[1,:,:2]
print(arayyy)
print("-----------------")
array3=arraytridi5[2,:,:]
print(array3[array3>20])
print("-----------------")


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
-----------------
[[10 11]
 [13 14]
 [16 17]]
-----------------
[21 22 23 24 25 26 27]
-----------------


#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [12]:
array_ran2 = np.random.randint(0,100,10)
print(array_ran2)
print("-----------------")

max_index = np.argmax(array_ran2)
min_index = np.argmin(array_ran2)

array_ran2[max_index] = 0
array_ran2[min_index] = 0

print("Array modificado:", array_ran2)



[91  7 12 91 28 35 72 72 81 96]
-----------------
Array modificado: [91  0 12 91 28 35 72 72 81  0]


#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [13]:
array_ran3 = np.random.randint(0,101,15)
print(array_ran3)
print("-----------------")

array_ran3ord=np.sort(array_ran3)
print(array_ran3ord)

[19  7 48 13 62 17 12 71 57  0 19 80  9 66 63]
-----------------
[ 0  7  9 12 13 17 19 19 48 57 62 63 66 71 80]


#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [14]:
array_ran4 = np.random.randint(0,101,(4,4))
print(array_ran4)
print("-----------------")

suma_fila = np.sum(array_ran4, axis = 1)
print(suma_fila)

[[70 86  7 22]
 [55 48 17 58]
 [45 44 19 81]
 [88 69 26 76]]
-----------------
[185 178 189 259]


#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

In [15]:
array_ran5 = np.random.randint(0,101,(5,5))
print(array_ran5)
print("-----------------")
array_ran5[:,0]=1
array_ran5[:,4]=1
array_ran5[:,1:4]=0
print(array_ran5)

[[74  2 30 39 49]
 [86 56 86 91 87]
 [22 26 23 60 31]
 [97 22 85 32 54]
 [45 19 74 48 80]]
-----------------
[[1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]]


#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [17]:
array_ran6 = np.random.randint(0,101,10)
print(array_ran6)
print("-----------------")

media = np.mean(array_ran6)
desviacion_estandar = np.std(array_ran6)

print("Array aleatorio:", array_ran6)
print("Media:", media)
print("Desviación estándar:", desviacion_estandar)


[18 73 19 35  6 77 78 16  2 64]
-----------------
Array aleatorio: [18 73 19 35  6 77 78 16  2 64]
Media: 38.8
Desviación estándar: 29.30801938036755


#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


In [20]:
arraytridi6 = np.arange(1, 25).reshape(2, 3, 4)
print(arraytridi6)
print("-----------------")
arraytridi6_transpuesto = np.transpose(arraytridi6, (2, 1, 0))

print(arraytridi6_transpuesto)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
-----------------
[[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]]


- Se junta cada valor con su homonimo de la otra matriz, formando matrices de 3x2 con los valores de cada columna creando 4 matrices correspondientes a las 4 columnas

#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


In [22]:
arraytridi7 = np.arange(1, 25).reshape(3, 4, 2)
print(arraytridi7)
print("-----------------")

arraytridi7_transpuesto = np.transpose(arraytridi7, (1, 0, 2))

print(arraytridi7_transpuesto)


[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]]
-----------------
[[[ 1  2]
  [ 9 10]
  [17 18]]

 [[ 3  4]
  [11 12]
  [19 20]]

 [[ 5  6]
  [13 14]
  [21 22]]

 [[ 7  8]
  [15 16]
  [23 24]]]


#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


In [23]:

arraytridi8 = np.arange(1, 25).reshape(3, 2, 4)
print(arraytridi8)
print("-----------------")
arraytridi7_rotado = np.transpose(arraytridi8, (2, 0, 1))
print(arraytridi7_rotado)



[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
-----------------
[[[ 1  5]
  [ 9 13]
  [17 21]]

 [[ 2  6]
  [10 14]
  [18 22]]

 [[ 3  7]
  [11 15]
  [19 23]]

 [[ 4  8]
  [12 16]
  [20 24]]]


#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


In [92]:
arraytridi9 = np.random.randint(-10, 11, size=(3, 4, 5))
print(arraytridi9)
print("------------------------------")

array_vacio = np.empty(arraytridi9.shape, dtype=object)
print(array_vacio)
print("------------------------------")

mediana = np.median(arraytridi9)
print(mediana)
maximo = np.max(arraytridi9)
print(maximo)
minimo = np.min(arraytridi9)
print(minimo)
print("------------------------------")

for i in range(arraytridi9.shape[0]):
    for j in range(arraytridi9.shape[1]):
        for k in range(arraytridi9.shape[2]):
            valor = arraytridi9[i, j, k]
            if valor == mediana:
                array_vacio[i, j, k] = "M"
            elif valor == maximo:
                array_vacio[i, j, k] = "MAX"
            elif valor == minimo:
                array_vacio[i, j, k] = "MIN"
            elif valor > mediana:
                array_vacio[i, j, k] = "X"
            else:
                array_vacio[i, j, k] = "Y"

print(array_vacio)


[[[ -7  -1   7  -6   9]
  [ -4   7   6  -5  -8]
  [  3 -10  -8   6   2]
  [  8   2  -9  -6   5]]

 [[ -5  -3  -9  -5   8]
  [ -6   7  -5   4   8]
  [ -8   1  -9  -7  -3]
  [ 10   8  -9  -9  -8]]

 [[  0   0  -7  -5  -6]
  [ -1   6   0  -9   5]
  [  4  -9  -5   2  -9]
  [  4   0   7   3   6]]]
------------------------------
[[[None None None None None]
  [None None None None None]
  [None None None None None]
  [None None None None None]]

 [[None None None None None]
  [None None None None None]
  [None None None None None]
  [None None None None None]]

 [[None None None None None]
  [None None None None None]
  [None None None None None]
  [None None None None None]]]
------------------------------
-1.0
10
-10
------------------------------
[[['Y' 'M' 'X' 'Y' 'X']
  ['Y' 'X' 'X' 'Y' 'Y']
  ['X' 'MIN' 'Y' 'X' 'X']
  ['X' 'X' 'Y' 'Y' 'X']]

 [['Y' 'Y' 'Y' 'Y' 'X']
  ['Y' 'X' 'Y' 'X' 'X']
  ['Y' 'X' 'Y' 'Y' 'Y']
  ['MAX' 'X' 'Y' 'Y' 'Y']]

 [['X' 'X' 'Y' 'Y' 'Y']
  ['M' 'X' 'X' 'Y' 'X']

#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.

In [91]:
array4x4 = np.random.randint(0,101,(4,4))

print(array4x4)

matriz = [
    [1, 2, 3, 4],
    [2, 6, 7, 8],
    [3, 10, 11, 12],
    [4, 14, 15, 16]]

def comparar_fila_columna(array4x4):
    for i in range(len(array4x4)):
        for j in range(len(array4x4)):
            iguales = True
            for k in range(len(array4x4)):
                if array4x4[i][k] != array4x4[k][j]: 
                    iguales = False
                    break  
            if iguales:
                return "Existe al menos una fila que es igual a una columna"
    return "No hay ninguna fila que coincida con una columna."
print(comparar_fila_columna(matriz))
print(comparar_fila_columna(array4x4))




[[96 79 99 12]
 [77 22  9 55]
 [18 45  4 30]
 [ 8 86 11 25]]
Existe al menos una fila que es igual a una columna
No hay ninguna fila que coincida con una columna.
